[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["app"]

[tool.ruff.lint]
select = ["E","F","I","B","UP","S","N","C90"]
ignore = ["E501","B008"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


