name: elt_dbt
version: 1.0.0
profile: default

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  elt_dbt:
    +materialized: table

