name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend - lint and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps (npm ci)
        run: npm ci

      - name: Prettier check
        run: npx prettier --check "src/**/*.{ts,tsx,css}"

      - name: ESLint
        run: npx eslint .

      - name: Next build
        run: npm run build

  backend:
    name: Backend - lint (ruff/black)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff black

      - name: Ruff check
        run: python -m ruff check app

      - name: Black check
        run: python -m black --check app


